name: nightly

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  publish:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ 17 ]

    name: Publish Mod
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}

      - name: Setup Gradle Caching
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: java-${{ matrix.java }}
          gradle-version: wrapper
          save-generated-gradle-jars: true
          save-local-build-cache: true
          save-gradle-dependencies-cache: true
          save-maven-dependencies-cache: true

          gradle-dependencies-cache-key: |
            ~/.gradle/caches/forge_gradle/
            ~/.gradle/caches/parchmentgradle/
            accesstransformer.cfg

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Give Gradle Execute Permissions
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: chmod +x ./gradlew

      - name: Generate Mod Data & Asset Files
        run: ./gradlew data

      - name: Build Mod JARs
        run: ./gradlew build

      - name: Upload Artifacts to GitHub Actions
        uses: actions/upload-artifact@v3
        with:
          name: Mod-Jars
          path: ./build/libs

      - name: Stop Gradle Deamons
        run: ./gradlew --stop

      - name: Cleanup Gradle Cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties